version: 2
updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@types/vscode"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 100
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "chore"
      - "dependencies"
      - "gh-actions"
